gpu_id: 0
seed: 123
train_models_path: ${P2MPP_DIR}/data/ShapeNet/Models/train
test_models_path: ${P2MPP_DIR}/data/ShapeNet/Models/test
images_path: ${P2MPP_DIR}/data/ShapeNet/Images
models_path: ${P2MPP_DIR}/models

datalists_base_path: ${P2MPP_DIR}/datalists
misc_results_path: ${P2MPP_DIR}/results_misc
train_results_path: ${P2MPP_DIR}/results_train
test_results_path: ${P2MPP_DIR}/results_test
coarse_results_path: ${P2MPP_DIR}/results_coarse

data_list: 'only_sofas'
coarse_experiment_name: 'only_sofas_test_20210319-181933'

mvp2m: 
  lr: 1e-5
  init_epoch: 0
  epochs: 50
  test_epoch: 50
  restore: false
  feat_dim: 2883
  name: coarse_mvp2m
  restored_model_path: ''
  train_file_path: ${P2MPP_DIR}/datalists/train_list.txt
  test_file_path: ${P2MPP_DIR}/datalists/test_list.txt
  batch_size: 1
  lr: 3e-5
  seed: 123
  hidden_dim: 192
  stage2_feat_dim: 339
  coord_dim: 3
p2mpp:
  # 3 + 3*(512+256+128+64)
  feat_dim: 2883
  # 3 + 3*(16+32+64)
  stage2_feat_dim: 339
  name: refine_p2mpp
  # about cnn
  load_cnn: yes
  restored_model_path: ''
  pre_trained_cnn_path: ${P2MPP_DIR}/models/refine_p2mpp
  cnn_step: 10
  # train
  lr: 1e-5
  epochs: 10
  init_epoch: 0
  batch_size: 1
  seed: 123
  hidden_dim: 192
  stage2_feat_dim: 339
  coord_dim: 3
  restore: false
  # test
  test_epoch: 10