lr: 1e-5
init_epoch: 0
epochs: 50
test_epoch: 50
restore: false
gpu_id: 0
is_debug: no
feat_dim: 2883
name: 'coarse_mvp2m'
save_path: '${P2MPP_DIR}/Models'
# train
train_file_path: ${P2MPP_DIR}/data_lists/train_list.txt
train_data_path: ${P2MPP_DIR}/ShapeNetModels/train
train_image_path: ${P2MPP_DIR}/ShapeNetImages
# test
test_file_path: ${P2MPP_DIR}/data_lists/test_list.txt
test_data_path: ${P2MPP_DIR}/ShapeNetModels/test
test_image_path: ${P2MPP_DIR}/ShapeNetImages
# coarse result
coarse_result_file_path: ${P2MPP_DIR}/data_lists/train_list.txt
coarse_result_data_path: ${P2MPP_DIR}/ShapeNetModels/train
coarse_result_image_path: ${P2MPP_DIR}/ShapeNetImages