is_debug: no
# 3 + 3*(512+256+128+64)
feat_dim: 2883
# 3 + 3*(16+32+64)
stage2_feat_dim: 339
name: 'refine_p2mpp'
save_path: '${P2MPP_DIR}/Models'
# about cnn
load_cnn: yes
pre_trained_cnn_path: ${P2MPP_DIR}/Models/coarse_mvp2m
cnn_step: 50
# train
lr: 1e-5
epochs: 10
init_epoch: 50
gpu_id: 0
restore: false
train_file_path: ${P2MPP_DIR}/data_lists/train_list.txt
train_data_path: ${P2MPP_DIR}/ShapeNetModels/train
train_image_path: ${P2MPP_DIR}/ShapeNetImages
train_mesh_root: ${P2MPP_DIR}/Results/coarse_mvp2m/coarse_intermediate/50
# test
test_epoch: 10
test_file_path: ${P2MPP_DIR}/data_lists/test_list.txt
test_data_path: ${P2MPP_DIR}/ShapeNetModels/test
test_image_path: ${P2MPP_DIR}/ShapeNetImages
test_mesh_root: ${P2MPP_DIR}/coarse_mvp2m/predict/50
