is_debug: no
# 3 + 3*(512+256+128+64)
feat_dim: 2883
# 3 + 3*(16+32+64)
stage2_feat_dim: 339
name: 'refine_p2mpp'
# about cnn
load_cnn: yes

## Can't be found, will have to retrain.
pre_trained_cnn_path: 'models/coarse_mvp2m/models'
cnn_step: 50
# train
lr: 1e-5
epochs: 10
init_epoch: 50
gpu_id: 0
restore: false
# test
test_epoch: 10